name: Try GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, githubsample-runner-staging]

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "vergola.github@knowdgeplus.net.au"
          git config --global user.name "kplus-vergola"
    
      - name: Deploy Application
        run: |
          cd C:/Users/Jezmahboi/Projects/githubsample

          git pull origin main
