name: Try GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, githubsample-runner-staging]

    steps:
      - name: Deploy Application
        run: |
          cd C:\Users\Jezmahboi\Projects\githubsample

          git pull origin main
